# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.2
_src_path: gl:lunik1/nix-flake-template
author: Corin Hoad
nixpkgs_channel: nixpkgs-unstable
project_description: A configurable wallpaper for nix systems
project_name: nix-wallpaper

